apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-account
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: test-irsa
  namespace: default
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
    - sleep
    - "300"
  serviceAccountName: "test-service-account"