apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  # The number of Pod replicas that should be running in the cluster.
  replicas: 1

  # The selector specifies how to identify Pods started by this Deployment.
  selector:
    matchLabels:
      app: django-container

  # The template describes the Pods that will be created.
  template:
    metadata:
      # Labels for the Pods that will be created, matching the selector above.
      labels:
        app: django-container
    spec:
      # List of containers within the Pod
      containers:
        - name: django
          image: kubernetes_django:0.0.2
           # Command to run when the container starts; overrides CMD in dockerfile
          command: ['/bin/bash', 'run.sh']
          ports:
            - containerPort: 8000

          # Environment variables for the container
          env:
            - name: POSTGRES_USER  # Name of environment variable
              valueFrom:
                secretKeyRef:
                  # Name of the Kubernetes Secret that contains the Postgres credentials
                  name: postgres-credentials
                  # Key within the Secret that holds the Postgres user
                  key: user

            - name: POSTGRES_PASSWORD  # Name of environment variable
              valueFrom:
                secretKeyRef:
                  # Name of the Kubernetes Secret that contains the Postgres credentials
                  name: postgres-credentials
                  # Key within the Secret that holds the Postgres password
                  key: password

            - name: POSTGRES_HOST  # Name of environment variable
              value: postgres-service

            - name: PYTHONUNBUFFERED # Ensure logs are printed even when running script in detached mode
              value: "0"
